import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import initAuth from '../initAuth';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Firebase Auth",
  description: "Generated by create next app",
};

initAuth();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
